# backend/integrations/figma_client.py
import requests, os

def create_figma_wireframe(prompt: str):
    figma_token = os.getenv("FIGMA_TOKEN")
    url = "https://api.figma.com/v1/files"
    headers = {"X-Figma-Token": figma_token}
    payload = {"name": f"Wireframe for {prompt}", "description": "Auto-generated by NERVA"}
    r = requests.post(url, headers=headers, json=payload)
    return {"figma_result": r.json()}
